# Generated by Django 6.0.7 on 2026-08-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_commissiontransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_downline_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mlm_level',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
