# Generated by Django 6.0.7 on 2026-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_sellerordersettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=5),
        ),
    ]
