# Generated by Django 6.0.7 on 2026-07-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerequest',
            name='rank',
            field=models.CharField(default='LV.0', max_length=20),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='total_downlines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='total_referral_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
