# Generated by Django 6.0.7 on 2026-09-02 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_brand_category_product_brand_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('age', models.PositiveSmallIntegerField()),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('pan_card', models.FileField(upload_to='seller_kyc/pan/')),
                ('aadhaar_card', models.FileField(upload_to='seller_kyc/aadhaar/')),
                ('bank_account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_account_name', models.CharField(max_length=150)),
                ('pickup_address', models.TextField()),
                ('pickup_pincode', models.CharField(max_length=10)),
                ('pickup_district', models.CharField(max_length=100)),
                ('pickup_state', models.CharField(max_length=100)),
                ('pickup_country', models.CharField(default='India', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
