# Generated by Django 6.0.7 on 2026-09-04 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_sellerwallettransaction_wallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOrderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company_rate', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('company_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('seller_rate', models.DecimalField(decimal_places=2, default=94.0, max_digits=5)),
                ('seller_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_settlement', to='accounts.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
