# Generated by Django 6.0.7 on 2026-09-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_product_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='buyer_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
