# Generated by Django 6.0.7 on 2026-09-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_sellerordersettlement_company_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_end',
            field=models.DateTimeField(blank=True, help_text='Offer end date and time', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special offer price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_start',
            field=models.DateTimeField(blank=True, help_text='Offer start date and time', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Regular selling price', max_digits=10),
        ),
    ]
