# Generated by Django 6.0.7 on 2026-09-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_sellerwallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerwallettransaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='sellerwallettransaction',
            name='order',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='wallet_balance',
            new_name='bonus_balance',
        ),
        migrations.DeleteModel(
            name='SellerWallet',
        ),
        migrations.DeleteModel(
            name='SellerWalletTransaction',
        ),
    ]
