# Generated by Django 6.0.7 on 2026-09-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_sellerprofile_delivered_at_sellerprofile_label_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='label_file',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='packed_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='seller_accepted_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='seller_note',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='shipped_at',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='label_file',
            field=models.FileField(blank=True, null=True, upload_to='shipping_labels/'),
        ),
        migrations.AddField(
            model_name='order',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
