# Generated by Django 6.0.7 on 2026-08-08 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order_status_order_tracking_id_order_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('rate', models.DecimalField(decimal_places=5, max_digits=7)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_transactions', to='accounts.order')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['level', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'beneficiary', 'level'), name='unique_order_beneficiary_level_commission')],
            },
        ),
    ]
